### PR TITLE
fix small error log in loggers.

### LINKED ISSUE #1410: bug:  Small Issue in Error messages in UDP and TCP loggers.
Small Issue in Error messages in UDP and TCP loggers.

### PR DESCRIPTION
**Pull request by Akayeshmantha**
Fix #1410

### CODE REVIEW

File: apisix/plugins/udp-logger.lua [hunk 1]
```diff
@@ -82,7 +82,7 @@ function _M.log(conf)
     local entry = log_util.get_full_log(ngx)
 
     if not entry.route_id then
-        core.log.error("failed to obtain the route id for tcp logger")
+        core.log.error("failed to obtain the route id for udo logger")
```
Comment (membphis) [inline apisix/plugins/udp-logger.lua:85]: typo

**Comment by Akayeshmantha** [comment]
@membphis  done
