### PR TITLE
change: don't strip square brackets from the IPv6

### LINKED ISSUE #816: bug: should not remove the square brackets of [IPv6] address literal in core.utils.parse_addr
Currently I choice to remove the square brackets because `core.utils.parse_ipv6` doesn't work if the square brackets are kept.

However, the OpenResty APIs (tcpsock:connect, balancer.set_current_peer, etc.) require the square brackets in the IPv6 address even though they are used without the port part. Admittedly, it would be better to fix in the OpenResty APIs side, but these APIs are created and widely adopted long time ago...

Therefore, to make the IPv6 upstream work, we need to keep the square brackets too. My proposal is modifying `core.utils.parse_addr` not to remove the brackets, and changing `core.utils.parse_ipv6` to accept the brackets.

What about your opinion?

### PR DESCRIPTION
**Pull request by spacewander**
The OpenResty APIs require the IPv6 literal wrapped inside a square brackets.
Also add tests for IPv6 upstream and update lua-resty-ipmatcher to 0.3.

Fix #816.

### CODE REVIEW

File: lua/apisix/core/utils.lua [hunk 1]
```diff
@@ -106,7 +106,7 @@ function _M.parse_addr(addr)
         local len = #addr
         if str_byte(addr, len) == right_bracket then
             -- addr in [ip:v6] format
-            return sub_str(addr, 2, len-1), default_port
+            return sub_str(addr, 1, len), default_port
```
Comment (membphis) [inline lua/apisix/core/utils.lua]: I think `sub_str(addr, 1, len)`  equal `addr` object, right?

**Comment by membphis** [comment]
I run the test cases `t/node/healthcheck-ipv6.t`, `t/node/remote-addr-ipv6.t` and `t/node/upstream-ipv6.t`, they work fine on my local computer .

File: rockspec/apisix-master-0.rockspec [hunk 2]
```diff
@@ -48,6 +48,7 @@ dependencies = {
     "lua-tinyyaml = 0.1",
     "iresty-nginx-lua-prometheus = 0.20190917",
     "jsonschema = 0.4",
+    "lua-resty-ipmatcher = 0.3",
```
Comment (membphis) [inline rockspec/apisix-master-0.rockspec]: We can remove this line, and update `lua-resty-radixtree` to `1.6-1`:

```diff
--- a/rockspec/apisix-master-0.rockspec
+++ b/rockspec/apisix-master-0.rockspec
@@ -41,14 +41,13 @@ dependencies = {
     "lua-resty-cookie = 0.1.0",
     "lua-resty-session = 2.24",
     "opentracing-openresty = 0.1",
-    "lua-resty-radixtree = 1.5",
+    "lua-resty-radixtree = 1.6-1",
     "lua-protobuf = 0.3.1",
     "lua-resty-openidc = 1.7.2-1",
     "luafilesystem = 1.7.0-2",
     "lua-tinyyaml = 0.1",
     "iresty-nginx-lua-prometheus = 0.20190917",
     "jsonschema = 0.4",
-    "lua-resty-ipmatcher = 0.3",
 }
```

File: lua/apisix/core/utils.lua (hunk 1 above)
Comment (spacewander) [reply lua/apisix/core/utils.lua]: @membphis 
Fixed.

File: rockspec/apisix-master-0.rockspec (hunk 2 above)
Comment (spacewander) [reply rockspec/apisix-master-0.rockspec]: @membphis 
I think it would be better to list lua-resty-ipmatcher as a dependency here since APISIX depends on it directly. If one day we remove lua-resty-radixtree, lua-resty-ipmatcher should not be removed.

Comment (membphis) [reply rockspec/apisix-master-0.rockspec]: You are right, we can fix this later.
